Add Questions
ChristianZimpelmann/labor_supply_norms pull request #1
Opened 2023-04-20 18:02 UTC by timmens

Add questions raised when presenting at the Applied Coffee.

2023-04-20 18:17 UTC, ChristianZimpelmann requested changes
Thanks! But I thought the feedback and questions rather fit to the admin repo. We can discuss if you disagree of course

2023-04-20 18:17 UTC, ChristianZimpelmann commented on src/labor_supply_norms/sandbox/questions/applied_micro_coffee_14_04_23.md
> +# Questions
I think the questions would rather fit in this repo: https://gitlab.iame.uni-bonn.de/ChristianZimpelmann/labor_supply_norms_admin

2023-04-20 18:17 UTC, ChristianZimpelmann commented on src/labor_supply_norms/data_management/task_impute_norms_ind_level.py
> +    for var in "norms_gender_cons_avg":
round brackets missing?

2023-04-20 21:02 UTC, timmens commented
Yes, thank you for mentioning it again. I've opened a PR in the correct repo where I added the feedback.

I think we can use this PR to fix the few pre-commit errors. I do not necessarily like the `(1,)` syntax for a tuple with only one element, so I'd also be fine with ignoring ruff's rule against looping over `[1]`; especially since I think the latter is more readable.

2023-04-21 05:49 UTC, ChristianZimpelmann commented
Thanks for fixing the pre-commit errors. 

> I think we can use this PR to fix the few pre-commit errors. I do not necessarily like the `(1,)` syntax for a tuple with only one element, so I'd also be fine with ignoring ruff's rule against looping over `[1]`; especially since I think the latter is more readable. 

So you would deactivate the rule converting those lists to sets in general or only for collections of one element only?
I don't mind changing lists to sets, but I agree that the comma after just one element is strange.

So I tend to prefer `(1)`. But don't have a strong opinion here.

2023-04-21 05:50 UTC, ChristianZimpelmann approved these changes
Feel free to implement your preferred changes.

2023-04-21 08:28 UTC, timmens commented
Except for the few cases I changed here, all other collections you iterate over are already tuples. I decided to stick with the tuple and the additional comma because it serves as a good reminder that we should either add more variables to the collection at some point or not loop over it at all.

2023-04-21 08:29 UTC, merged